const query=new URLSearchParams(location.search); const postId=query.get('id');
async function loadExplore(){const box=document.querySelector('#explore-posts');try{const {posts}=await api('/api/posts');box.innerHTML=posts.length?posts.map(postCard).join(''):'<p class="empty-state">No travel posts available yet.</p>';}catch(e){box.innerHTML=`<p class="empty-state">${escapeHTML(e.message)}</p>`;}}
async function loadDetails(){const box=document.querySelector('#post-detail');if(!postId){box.innerHTML='<p class="empty-state">Post not found.</p>';return;}try{const [{post},{comments}]=await Promise.all([api(`/api/posts/${postId}`),api(`/api/posts/${postId}/comments`)]);document.title=`${post.title} · Wanderly`;box.innerHTML=`<img class="detail-cover" src="${escapeHTML(post.image)}" alt="${escapeHTML(post.location)}"><article class="detail-content"><p class="eyebrow">↗ ${escapeHTML(post.location)}</p><h1>${escapeHTML(post.title)}</h1><p class="lead">By ${escapeHTML(post.author)} · ${formatDate(post.created_at)}</p><button class="like-button ${post.liked?'liked':''}" id="like-button">${post.liked?'❤️ Liked':'🤍 Like'} · <span id="like-count">${post.like_count}</span></button><div class="story-text">${escapeHTML(post.description)}</div><section class="comments"><h2>Comments <span class="muted" id="comment-count">(${post.comment_count})</span></h2><form id="comment-form" class="comment-form"><input name="comment_text" maxlength="2000" placeholder="Write a comment…" required><button class="button">Post comment</button></form><p class="form-message" aria-live="polite"></p><div id="comment-list">${commentMarkup(comments)}</div></section></article>`;
 document.querySelector('#like-button').addEventListener('click',async()=>{try{const liked=document.querySelector('#like-button').classList.contains('liked');const result=await api(`/api/posts/${postId}/like`,{method:liked?'DELETE':'POST'});document.querySelector('#like-button').classList.toggle('liked',result.liked);document.querySelector('#like-button').innerHTML=`${result.liked?'❤️ Liked':'🤍 Like'} · <span id="like-count">${result.count}</span>`;}catch(e){if(e.message.includes('log in'))location.href='/pages/login.html';else alert(e.message);}});
 document.querySelector('#comment-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,msg=document.querySelector('.comments .form-message');try{const data=await api(`/api/posts/${postId}/comments`,{method:'POST',body:JSON.stringify({comment_text:new FormData(form).get('comment_text')})});const list=document.querySelector('#comment-list');list.insertAdjacentHTML('afterbegin',commentMarkup([data.comment]));const count=document.querySelector('#comment-count');count.textContent=`(${Number(count.textContent.replace(/\D/g,''))+1})`;form.reset();}catch(err){msg.textContent=err.message;if(err.message.includes('log in'))setTimeout(()=>location.href='/pages/login.html',700);}});
 }catch(e){box.innerHTML=`<p class="empty-state">${escapeHTML(e.message)}</p>`;}}
function commentMarkup(rows){return rows.length?rows.map(c=>`<article class="comment"><strong>${escapeHTML(c.author)}</strong><time>${formatDate(c.created_at)}</time><p>${escapeHTML(c.comment_text)}</p></article>`).join(''):'<p class="muted">No comments yet. Be the first to comment!</p>';}
async function postForm(){const form=document.querySelector('#post-form');if(!form)return;const editing=document.body.dataset.page==='edit-post';if(editing){if(!postId){location.href='/pages/profile.html';return;}try{const {post}=await api(`/api/posts/${postId}`);const me=await api('/api/auth/me');if(post.user_id!==me.user.id)throw Error('You are not allowed to edit this post.');for(const key of ['title','location','description'])form.elements[key].value=post[key];document.querySelector('#existing-image').innerHTML=`<img class="preview-image" src="${escapeHTML(post.image)}" alt="Current travel image">`;}catch(e){form.querySelector('.form-message').textContent=e.message;return;}}
form.addEventListener('submit',async e=>{e.preventDefault();const msg=form.querySelector('.form-message'),button=form.querySelector('button');msg.textContent='';button.disabled=true;button.textContent='Saving…';try{const data=await api(editing?`/api/posts/${postId}`:'/api/posts',{method:editing?'PUT':'POST',body:new FormData(form)});location.href=editing?`/pages/post-details.html?id=${postId}`:'/pages/profile.html';}catch(err){msg.textContent=err.message;}finally{button.disabled=false;button.textContent=editing?'Save changes ↗':'Publish story ↗';}});}
const page=document.body.dataset.page;if(page==='explore')loadExplore();if(page==='details')loadDetails();if(page==='create'||page==='edit-post')postForm();
