const express=require('express'); const path=require('path'); const cookieParser=require('cookie-parser'); const helmet=require('helmet'); const rateLimit=require('express-rate-limit');
const {notFound,errorHandler}=require('./middleware/errorMiddleware');
const app=express();
app.use(helmet({contentSecurityPolicy:{directives:{...helmet.contentSecurityPolicy.getDefaultDirectives(),'img-src':["'self'",'data:','https:'],'style-src':["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],'font-src':["'self'",'data:','https://fonts.gstatic.com']}}}));
app.use(express.json({limit:'100kb'})); app.use(express.urlencoded({extended:false})); app.use(cookieParser());
app.use('/api/auth',rateLimit({windowMs:15*60*1000,limit:100,standardHeaders:true,legacyHeaders:false}));
app.use('/uploads',express.static(path.join(__dirname,'uploads')));
app.use('/api/auth',require('./routes/authRoutes')); app.use('/api/posts',require('./routes/postRoutes')); app.use('/api/comments',require('./routes/commentRoutes')); app.use('/api/users',require('./routes/userRoutes'));
app.use(express.static(path.join(__dirname,'..','client'))); app.use(notFound); app.use(errorHandler);
module.exports=app;
